PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_USE MODULE %_P_USE .

FIELD !P_COMP MODULE %_P_COMP .

FIELD !P_PERIOT MODULE %_P_PERIOT .

FIELD !P_PERIOS MODULE %_P_PERIOS .

FIELD !P_SUMMAR MODULE %_P_SUMMAR .

FIELD !P_FILE MODULE %_P_FILE .


CHAIN.
  FIELD P_USE .
  FIELD P_COMP .
  FIELD P_PERIOT .
  FIELD P_PERIOS .
  FIELD P_SUMMAR .
  FIELD P_FILE .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

FIELD !P_ROLE MODULE %_P_ROLE .

FIELD !P_FILER MODULE %_P_FILER .

FIELD !P_FILER2 MODULE %_P_FILER2 .

FIELD !P_FILER3 MODULE %_P_FILER3 .

FIELD !P_FILER4 MODULE %_P_FILER4 .

FIELD !P_FILER5 MODULE %_P_FILER5 .


CHAIN.
  FIELD P_ROLE .
  FIELD P_FILER .
  FIELD P_FILER2 .
  FIELD P_FILER3 .
  FIELD P_FILER4 .
  FIELD P_FILER5 .
    MODULE %_BLOCK_1000008.
ENDCHAIN.

FIELD !P_GENE MODULE %_P_GENE .

FIELD !P_FILEG1 MODULE %_P_FILEG1 .


CHAIN.
  FIELD P_GENE .
  FIELD P_FILEG1 .
    MODULE %_BLOCK_1000016.
ENDCHAIN.

CHAIN.
  FIELD P_USE .
  FIELD P_COMP .
  FIELD P_PERIOT .
  FIELD P_PERIOS .
  FIELD P_SUMMAR .
  FIELD P_FILE .
  FIELD P_ROLE .
  FIELD P_FILER .
  FIELD P_FILER2 .
  FIELD P_FILER3 .
  FIELD P_FILER4 .
  FIELD P_FILER5 .
  FIELD P_GENE .
  FIELD P_FILEG1 .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.