title: SRYA extractor
logo: https://github.com/NovisEuforia/SRYA_extractor/blob/master/assests/img/logo.jpg
description: IDR for the R&A framework
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
